<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="PrintServiceImplService" targetNamespace="http://print/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="http://print/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap12="http://schemas.xmlsoap.org/wsdl/soap12/">
  <wsdl:types>
    <xs:schema elementFormDefault="unqualified" targetNamespace="http://print/" version="1.0" xmlns:tns="http://print/" xmlns:xs="http://www.w3.org/2001/XMLSchema">

  <xs:element name="print" type="tns:print"/>

  <xs:element name="printResponse" type="tns:printResponse"/>

  <xs:complexType name="print">
    <xs:sequence>
      <xs:element minOccurs="0" name="arg0" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>

  <xs:complexType name="printResponse">
    <xs:sequence/>
  </xs:complexType>

</xs:schema>
  </wsdl:types>
  <wsdl:message name="print">
    <wsdl:part name="parameters" element="tns:print">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="printResponse">
    <wsdl:part name="parameters" element="tns:printResponse">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="PrintService">
    <wsdl:operation name="print">
      <wsdl:input name="print" message="tns:print">
    </wsdl:input>
      <wsdl:output name="printResponse" message="tns:printResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="PrintServiceImplServiceSoapBinding" type="tns:PrintService">
    <soap12:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="print">
      <soap12:operation soapAction="" style="document"/>
      <wsdl:input name="print">
        <soap12:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="printResponse">
        <soap12:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="PrintServiceImplService">
    <wsdl:port name="PrintServiceImplPort" binding="tns:PrintServiceImplServiceSoapBinding">
      <soap12:address location="http://localhost:8080/Esercizio4.1/services/PrintServiceImplPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
