
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package math;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-26T14:57:05.981+01:00
 * Generated source version: 3.3.1
 *
 */
public class MathClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://math/", "MathServiceImplService");
        QName portName = new QName("http://math/", "MathServiceImplPort");

        Service service = Service.create(serviceName);
//        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
//                        "http://localhost:9090/MathServiceImplPort");
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                "http://localhost:8080/Esercizio4.2/services/MathServiceImplPort"); 
        
        	
        math.Math client = service.getPort(portName,  math.Math.class);

        // Insert code to invoke methods on the client here
        System.out.println("Multiplication 3*4 = "+client.multiply(3, 4));
        System.out.println("Division 3/4 = "+client.divide(3, 4));
        System.out.println("Factorial of 4 = "+client.factOf(4));
    }

}