
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package it.unisannio.hotelAgency;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;


/**
 * This class was generated by Apache CXF 3.3.1 2019-03-29T09:28:29.237+01:00
 * Generated source version: 3.3.1
 *
 */
public class HotelAgencyServiceClient {

	public static void main(String[] args) throws Exception {
		QName serviceName = new QName("http://hotelAgency.unisannio.it/", "HotelAgencyServiceImplService");
		QName portName = new QName("http://hotelAgency.unisannio.it/", "HotelAgencyServiceImplPort");

		Service service = Service.create(serviceName);
		service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
				"http://localhost:6000/Esercizio4.4/services/HotelAgencyServiceImplPort");
		it.unisannio.hotelAgency.HotelAgencyService client = service.getPort(portName,
				it.unisannio.hotelAgency.HotelAgencyService.class);

		// Insert code to invoke methods on the client here

		//search
		System.out.println("\n***************search****************");
		Date checkin = (Date) (new SimpleDateFormat("dd-MM-yyyy")).parse("01-03-2019");
		Date checkout = (Date) (new SimpleDateFormat("dd-MM-yyyy")).parse("30-06-2019");

		System.out.println(client.getHotelDetails(client.search(checkin, checkout, "Benevento").get(0)));
		
		//reserve
		System.out.println("\n****************reserve**************");
		int creditCard = 123;
		Rate rate = new Rate(1, "Single", checkin, checkout, 130.0);
		int confId=client.reserve(rate, creditCard);

		System.out.println("confId: " + confId);
		
		//getConfirmationId
		System.out.println("\n*******************getConfirmationId********************");
		System.out.println("confirmationDetails: " + client.getConfirmationDetails(confId));
		
		//listMyBooking
		System.out.println("\n****************listMyBooking***********************");
		List<Integer> hotelId=client.listMyBooking(creditCard);
		
		for(Integer i: hotelId) {
			System.out.println(client.getHotelDetails(i));
		}
		
		
	}

}