
package it.unisannio.hotelAgency;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-29T09:28:29.212+01:00
 * Generated source version: 3.3.1
 *
 */

public class HotelAgencyServiceServer{

    protected HotelAgencyServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new it.unisannio.hotelAgency.HotelAgencyServiceImpl();
        String address = "http://localhost:9090/HotelAgencyServiceImplPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new HotelAgencyServiceServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

