
package math;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-28T16:52:44.141+01:00
 * Generated source version: 3.3.1
 *
 */

public class MathServiceServer{

    protected MathServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new math.MathServiceImpl();
        String address = "http://localhost:9090/MathServiceImplPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new MathServiceServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

