
package print;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-26T14:41:19.688+01:00
 * Generated source version: 3.3.1
 *
 */

public class PrintServiceServer{

    protected PrintServiceServer() throws Exception {
        System.out.println("Starting Server");
        Object implementor = new print.PrintServiceImpl();
        String address = "http://localhost:9090/PrintServiceImplPort";
        Endpoint.publish(address, implementor);
    }

    public static void main(String args[]) throws Exception {
        new PrintServiceServer();
        System.out.println("Server ready...");

        Thread.sleep(5 * 60 * 1000);
        System.out.println("Server exiting");
        System.exit(0);
    }
}

