
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package print;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.soap.SOAPBinding;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-26T14:41:19.722+01:00
 * Generated source version: 3.3.1
 *
 */
public class PrintServiceClient {

    public static void main(String[] args) throws Exception {
        QName serviceName = new QName("http://print/", "PrintServiceImplService");
        QName portName = new QName("http://print/", "PrintServiceImplPort");

        Service service = Service.create(serviceName);
        //service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
           //             "http://localhost:9090/PrintServiceImplPort");
        service.addPort(portName, SOAPBinding.SOAP11HTTP_BINDING,
                "http://localhost:6000/Esercizio4.1/services/PrintServiceImplPort"); 
        
        
        print.PrintService client = service.getPort(portName,  print.PrintService.class);

        // Insert code to invoke methods on the client here
        client.print("ciao");
    }

}